-- Create a table for storing contact form submissions
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Allow anyone (anon) to insert data
create policy "Enable insert for all users"
  on public.contacts
  for insert
  to anon
  with check (true);

-- Allow authenticated users to view data (optional, for admin dashboard later)
create policy "Enable read access for authenticated users only"
  on public.contacts
  for select
  to authenticated
  using (true);

-- Create a table for storing internship applications
create table if not exists public.internship_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  position text not null
);

-- Enable Row Level Security (RLS)
alter table public.internship_applications enable row level security;

-- Allow anyone (anon) to insert data
create policy "Enable insert for all users"
  on public.internship_applications
  for insert
  to anon
  with check (true);

-- Allow authenticated users to view data (optional, for admin dashboard later)
create policy "Enable read access for authenticated users only"
  on public.internship_applications
  for select
  to authenticated
  using (true);
